From onnx/aigrpc-server
RUN wget -O googletest.tar.gz https://github.com/google/googletest/archive/release-1.11.0.tar.gz
RUN tar xf googletest.tar.gz;mv googletest-release-1.11.0 googletest;cd googletest;cmake -DBUILD_SHARED_LIBS=ON .;make
