FROM onnx/aigrpc-server:ff
RUN apt-get install -y gdb
RUN cd aigrpc-server \
    && mkdir -p cmake/debug; cd cmake/debug \
    && cmake -DCMAKE_BUILD_TYPE=Debug ../.. \
    && cmake --build . \
    && cd ../../tests \
    && for dir in models/*/; do echo $dir; ls $dir/model.onnx|xargs onnx-mlir; done; cp -r models ../cmake/debug/

ENTRYPOINT ["/bin/bash"]
