FROM onnx/aigrpc-server:ff

RUN apt-get install wget \
    && wget -O googletest.tar.gz https://github.com/google/googletest/archive/release-1.11.0.tar.gz \
    && tar xf googletest.tar.gz;mv googletest-release-1.11.0 googletest \
    && cd googletest;cmake -DBUILD_SHARED_LIBS=ON .;make;make install \
    && rm -rf googletest \
    && ldconfig


RUN cd aigrpc-server/cmake/build/tests;make \
    && cd ../../../tests; for dir in models/*/; do echo $dir; ls ${dir}model.onnx|xargs onnx-mlir; done \
    && cp -r models ../cmake/build/ \
    && cp ../cmake/build/tests/grpc-test ../cmake/build \
    && cd ../java; mvn verify 


ENTRYPOINT ["/bin/bash"]